#!/bin/bash
## usage: cmd username passwd
## can be replaced by wwuseradd?
useradd $1
echo $2 | passwd $1 --stdin

# this will setup ww .ssh for the user with cluster-env
echo user $1 added on: 
su -u $1 -c 'date'

wwsh -y file import /etc/passwd
wwsh -y file import /etc/group
wwsh -y file import /etc/shadow
wwsh -y provision set --fileadd passwd,group,shadow
wwsh file sync

## wait many(3-5?) minuts for the account to take effect in all nodes
## FIX ME:some nodes have issue file ownership=nobody, reboot fixed it
