#!/bin/bash
## utility to caluclate CPU usage precisely
read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.25
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))
echo cpu `bc -l <<< "scale=2; 100*( ($total-$prevtotal) - ($idle-$previdle) ) / ($total-$prevtotal)"` % 
